// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.1
// source: plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type ClusterContextChangedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContextName    string                 `protobuf:"bytes,1,opt,name=contextName,proto3" json:"contextName,omitempty"`
	KubeconfigPath string                 `protobuf:"bytes,2,opt,name=kubeconfigPath,proto3" json:"kubeconfigPath,omitempty"`
	Timestamp      string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClusterContextChangedEvent) Reset() {
	*x = ClusterContextChangedEvent{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterContextChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterContextChangedEvent) ProtoMessage() {}

func (x *ClusterContextChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterContextChangedEvent.ProtoReflect.Descriptor instead.
func (*ClusterContextChangedEvent) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterContextChangedEvent) GetContextName() string {
	if x != nil {
		return x.ContextName
	}
	return ""
}

func (x *ClusterContextChangedEvent) GetKubeconfigPath() string {
	if x != nil {
		return x.KubeconfigPath
	}
	return ""
}

func (x *ClusterContextChangedEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PluginEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,3,opt,name=payloadJson,proto3" json:"payloadJson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEventRequest) Reset() {
	*x = PluginEventRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEventRequest) ProtoMessage() {}

func (x *PluginEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEventRequest.ProtoReflect.Descriptor instead.
func (*PluginEventRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginEventRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PluginEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\tpluginapi\"\a\n" +
	"\x05Empty\"\x84\x01\n" +
	"\x1aClusterContextChangedEvent\x12 \n" +
	"\vcontextName\x18\x01 \x01(\tR\vcontextName\x12&\n" +
	"\x0ekubeconfigPath\x18\x02 \x01(\tR\x0ekubeconfigPath\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"p\n" +
	"\x12PluginEventRequest\x12\x1a\n" +
	"\bpluginId\x18\x01 \x01(\tR\bpluginId\x12\x1c\n" +
	"\teventName\x18\x02 \x01(\tR\teventName\x12 \n" +
	"\vpayloadJson\x18\x03 \x01(\tR\vpayloadJson2\x98\x01\n" +
	"\x06Plugin\x12P\n" +
	"\x13ClusterContextWatch\x12\x10.pluginapi.Empty\x1a%.pluginapi.ClusterContextChangedEvent0\x01\x12<\n" +
	"\tEmitEvent\x12\x1d.pluginapi.PluginEventRequest\x1a\x10.pluginapi.EmptyB2Z0github.com/litelensapp/litelens/packages/core/pbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: pluginapi.Empty
	(*ClusterContextChangedEvent)(nil), // 1: pluginapi.ClusterContextChangedEvent
	(*PluginEventRequest)(nil),         // 2: pluginapi.PluginEventRequest
}
var file_plugin_proto_depIdxs = []int32{
	0, // 0: pluginapi.Plugin.ClusterContextWatch:input_type -> pluginapi.Empty
	2, // 1: pluginapi.Plugin.EmitEvent:input_type -> pluginapi.PluginEventRequest
	1, // 2: pluginapi.Plugin.ClusterContextWatch:output_type -> pluginapi.ClusterContextChangedEvent
	0, // 3: pluginapi.Plugin.EmitEvent:output_type -> pluginapi.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
