// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: plugin.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_ClusterContextWatch_FullMethodName   = "/pluginapi.Plugin/ClusterContextWatch"
	Plugin_ActiveNamespacesWatch_FullMethodName = "/pluginapi.Plugin/ActiveNamespacesWatch"
	Plugin_EmitEvent_FullMethodName             = "/pluginapi.Plugin/EmitEvent"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginClient interface {
	ClusterContextWatch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterContextChangedEvent], error)
	ActiveNamespacesWatch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActiveNamespacesChangedEvent], error)
	EmitEvent(ctx context.Context, in *PluginEventRequest, opts ...grpc.CallOption) (*Empty, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) ClusterContextWatch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterContextChangedEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plugin_ServiceDesc.Streams[0], Plugin_ClusterContextWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ClusterContextChangedEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_ClusterContextWatchClient = grpc.ServerStreamingClient[ClusterContextChangedEvent]

func (c *pluginClient) ActiveNamespacesWatch(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActiveNamespacesChangedEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plugin_ServiceDesc.Streams[1], Plugin_ActiveNamespacesWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ActiveNamespacesChangedEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_ActiveNamespacesWatchClient = grpc.ServerStreamingClient[ActiveNamespacesChangedEvent]

func (c *pluginClient) EmitEvent(ctx context.Context, in *PluginEventRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Plugin_EmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
type PluginServer interface {
	ClusterContextWatch(*Empty, grpc.ServerStreamingServer[ClusterContextChangedEvent]) error
	ActiveNamespacesWatch(*Empty, grpc.ServerStreamingServer[ActiveNamespacesChangedEvent]) error
	EmitEvent(context.Context, *PluginEventRequest) (*Empty, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) ClusterContextWatch(*Empty, grpc.ServerStreamingServer[ClusterContextChangedEvent]) error {
	return status.Error(codes.Unimplemented, "method ClusterContextWatch not implemented")
}
func (UnimplementedPluginServer) ActiveNamespacesWatch(*Empty, grpc.ServerStreamingServer[ActiveNamespacesChangedEvent]) error {
	return status.Error(codes.Unimplemented, "method ActiveNamespacesWatch not implemented")
}
func (UnimplementedPluginServer) EmitEvent(context.Context, *PluginEventRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitEvent not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call panics, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_ClusterContextWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).ClusterContextWatch(m, &grpc.GenericServerStream[Empty, ClusterContextChangedEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_ClusterContextWatchServer = grpc.ServerStreamingServer[ClusterContextChangedEvent]

func _Plugin_ActiveNamespacesWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).ActiveNamespacesWatch(m, &grpc.GenericServerStream[Empty, ActiveNamespacesChangedEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_ActiveNamespacesWatchServer = grpc.ServerStreamingServer[ActiveNamespacesChangedEvent]

func _Plugin_EmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).EmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_EmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).EmitEvent(ctx, req.(*PluginEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluginapi.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmitEvent",
			Handler:    _Plugin_EmitEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ClusterContextWatch",
			Handler:       _Plugin_ClusterContextWatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ActiveNamespacesWatch",
			Handler:       _Plugin_ActiveNamespacesWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
