import { useDetailDrawerContext } from "@/app/clusters/shared/components/details/DetailDrawerContext";

export function useResourceLinks(): Record<string, (namespace: string, name: string) => void> {
  const {
    onToggleClusterRoleDetail,
    onToggleClusterRoleBindingDetail,
    onToggleConfigMapDetail,
    onToggleCronJobDetail,
    onToggleDaemonSetDetail,
    onToggleDeploymentDetail,
    onToggleEndpointDetail,
    onToggleEndpointSliceDetail,
    onToggleEventDetail,
    onToggleHPADetail,
    onToggleIngressDetail,
    onToggleIngressClassDetail,
    onToggleJobDetail,
    onToggleLease,
    onToggleLimitRangeDetail,
    onToggleNamespaceDetail,
    onToggleNetworkPolicyDetail,
    onToggleNodeDetail,
    onTogglePersistentVolumeClaimDetail,
    onTogglePersistentVolumeDetail,
    onTogglePodDetail,
    onTogglePodDisruptionBudgetDetail,
    onTogglePriorityClass,
    onToggleReplicaSetDetail,
    onToggleResourceQuotaDetail,
    onToggleRoleDetail,
    onToggleRoleBindingDetail,
    onToggleSecretDetail,
    onToggleServiceDetail,
    onToggleServiceAccountDetail,
    onToggleStatefulSetDetail,
    onToggleStorageClassDetail,
    onToggleValidatingWebhookConfigDetail,
  } = useDetailDrawerContext();

  return {
    clusterrole: (_ns, name) => onToggleClusterRoleDetail(name),
    clusterrolebinding: (_ns, name) => onToggleClusterRoleBindingDetail(name),
    configmap: onToggleConfigMapDetail,
    cronjob: onToggleCronJobDetail,
    daemonset: onToggleDaemonSetDetail,
    deployment: onToggleDeploymentDetail,
    endpoints: onToggleEndpointDetail,
    endpointslice: onToggleEndpointSliceDetail,
    event: onToggleEventDetail,
    horizontalpodautoscaler: onToggleHPADetail,
    ingress: onToggleIngressDetail,
    ingressclass: (_ns, name) => onToggleIngressClassDetail(name),
    job: onToggleJobDetail,
    lease: onToggleLease,
    limitrange: onToggleLimitRangeDetail,
    namespace: (_ns, name) => onToggleNamespaceDetail(name),
    networkpolicy: onToggleNetworkPolicyDetail,
    node: (_ns, name) => onToggleNodeDetail(name),
    persistentvolume: (_ns, name) => onTogglePersistentVolumeDetail(name),
    persistentvolumeclaim: onTogglePersistentVolumeClaimDetail,
    pod: onTogglePodDetail,
    poddisruptionbudget: onTogglePodDisruptionBudgetDetail,
    priorityclass: (_ns, name) => onTogglePriorityClass(name),
    replicaset: onToggleReplicaSetDetail,
    resourcequota: onToggleResourceQuotaDetail,
    role: onToggleRoleDetail,
    rolebinding: onToggleRoleBindingDetail,
    secret: onToggleSecretDetail,
    service: onToggleServiceDetail,
    serviceaccount: onToggleServiceAccountDetail,
    statefulset: onToggleStatefulSetDetail,
    storageclass: (_ns, name) => onToggleStorageClassDetail(name),
    validatingwebhookconfiguration: (_ns, name) => onToggleValidatingWebhookConfigDetail(name),
  };
}
